export {StampedTemplate, Part} from './stamped-template.js'
export {parse} from './template-string-parser.js'
export {AttributeTemplatePart, AttributeValueSetter} from './attribute-template-part.js'
export {propertyIdentity, propertyIdentityOrBooleanAttribute} from './processors.js'
export type {StampedTemplateProcessor} from './stamped-template.js'
