name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-node:
    name: Test on Node.js
    runs-on: macos-latest
    steps:
    - name: Checkout the project
      uses: actions/checkout@v3
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js 14.7.0
      uses: actions/setup-node@v3
      with:
        node-version: '17'
    - name: Install dependencies
      run: npm i
    - name: Run Node.js Tests
      run: npm run test
